/**
 * Enums from the Crownstone router protocol.
 */

export const GenericPacketType = {
  PACKET_TYPE_CONTROL: 0,
  PACKET_TYPE_RESULT: 1,
  PACKET_TYPE_DATA: 2,
};

export const CommandPacketType = {
  COMMAND_TYPE_SET_CONFIG: 0,
  COMMAND_TYPE_GET_CONFIG: 1,
  COMMAND_TYPE_WIFI_CONNECT: 2,
  COMMAND_TYPE_WIFI_DISCONNECT: 3,
  COMMAND_TYPE_RESET: 4,
  COMMAND_TYPE_FACTORY_RESET: 5,
  COMMAND_TYPE_SWITCH: 6,
};

export const ResultPacketType = {
  RESULT_TYPE_SUCCES: 0,
  RESULT_TYPE_WAIT_FOR_SUCCESS: 1,
  RESULT_TYPE_SUCCESS_NO_CHANGE: 2,
  RESULT_TYPE_BUFFER_UNASSIGNED: 8,
  RESULT_TYPE_BUFFER_TOO_SMALL: 9,
  RESULT_TYPE_WRONG_PAYLOAD_LENGTH: 16,
  RESULT_TYPE_UNKNOWN_TYPE: 17,
  RESULT_TYPE_NO_SPACE: 18,
  RESULT_TYPE_BUSY: 19,
  RESULT_TYPE_TIMEOUT: 20,
  RESULT_TYPE_CANCELED: 21,
  RESULT_TYPE_PROTOCOL_UNSUPPORTED: 22,
  RESULT_TYPE_MISMATCH: 23,
  RESULT_TYPE_NOT_IMPLEMENTED: 32,
  RESULT_TYPE_NOT_INITIALIZED: 33,
  RESULT_TYPE_READ_FAILED: 34,
  RESULT_TYPE_UNSPECIFIED: 128,
};

export const InstanceType = {
  INSTANCE_TYPE_ESP32: 0,
  INSTANCE_TYPE_UART: 1,
  INSTANCE_TYPE_BLE: 2,
  INSTANCE_TYPE_CLOUD: 3,
};

export const InstanceIdEsp32 = {
  INSTANCE_ID_ESP32: 0,
};

export const InstanceIdUart = {
  INSTANCE_ID_UART_RS485: 0,
  INSTANCE_ID_UART_RS232: 1,
  INSTANCE_ID_UART_CM4: 2,
};

export const InstanceIdCloud = {
  INSTANCE_ID_CLOUD: 0,
};

export const InstanceIdBle = {
  INSTANCE_ID_BLE_MESH: 0,
  INSTANCE_ID_BLE_CLIENT: 1,
};

export const ConfigType = {
  CONFIG_TYPE_WIFI_SSID: 0,
  CONFIG_TYPE_WIFI_PSK: 1,
  CONFIG_TYPE_UART_BAUDRATE: 2,
};

export const ConfigPersistenceMode = {
  CONFIG_PERSISTENCE_NODE_TEMPORARY: 0,
  CONFIG_PERSISTENCE_MODE_STORED: 1,
};
