/**
 * Enums from the Crownstone router protocol & Crownstone protocol.
 */

export const GenericPacketType = {
  PACKET_TYPE_CONTROL: 0,
  PACKET_TYPE_RESULT: 1,
  PACKET_TYPE_DATA: 2,
};

export const CommandPacketType = {
  COMMAND_TYPE_SET_CONFIG: 0,
  COMMAND_TYPE_GET_CONFIG: 1,
  COMMAND_TYPE_WIFI_CONNECT: 2,
  COMMAND_TYPE_WIFI_DISCONNECT: 3,
  COMMAND_TYPE_RESET: 4,
  COMMAND_TYPE_FACTORY_RESET: 5,
  COMMAND_TYPE_SWITCH: 6,
  COMMAND_TYPE_REQUEST: 7,
};

export const ResultPacketType = {
  RESULT_TYPE_SUCCES: 0,
  RESULT_TYPE_WAIT_FOR_SUCCESS: 1,
  RESULT_TYPE_SUCCESS_NO_CHANGE: 2,
  RESULT_TYPE_BUFFER_TOO_SMALL: 8,
  RESULT_TYPE_WRONG_PAYLOAD_LENGTH: 16,
  RESULT_TYPE_UNKNOWN_TYPE: 17,
  RESULT_TYPE_TIMEOUT: 18,
  RESULT_TYPE_CANCELED: 19,
  RESULT_TYPE_PROTOCOL_UNSUPPORTED: 20,
  RESULT_TYPE_MISMATCH: 21,
  RESULT_TYPE_NOT_IMPLEMENTED: 32,
  RESULT_TYPE_NOT_INITIALIZED: 33,
  RESULT_TYPE_READ_FAILED: 34,
  RESULT_TYPE_EVENT_UNHANDELED: 35,
  RESULT_TYPE_UNSPECIFIED: 128,
};

export const InstanceId = {
  INSTANCE_ID_UNKNOWN: 0,
  INSTANCE_ID_ESP32: 1,
  INSTANCE_ID_UART_RS485: 2,
  INSTANCE_ID_UART_RS232: 3,
  INSTANCE_ID_UART_CM4: 4,
  INSTANCE_ID_CLOUD: 5,
  INSTANCE_ID_BLE_CROWNSTONE_MESH: 6,
  INSTANCE_ID_BLE_CROWNSTONE_PERIPHERAL: 7,
};

export const ConfigType = {
  CONFIG_TYPE_WIFI_SSID: 0,
  CONFIG_TYPE_WIFI_PSK: 1,
  CONFIG_TYPE_UART_BAUDRATE: 2,
};

export const SetConfigPersistenceMode = {
  SET_CONFIG_PERSISTENCE_NODE_TEMPORARY: 0,
  SET_CONFIG_PERSISTENCE_MODE_STORED: 1,
};

export const GetConfigPersistenceMode = {
  GET_CONFIG_PERSISTENCE_MODE_CURRENT: 0,
  GET_CONFIG_PERSISTENCE_MODE_STORED: 1,
  GET_CONFIG_PERSISTENCE_MODE_FIRMWARE_DEFAULT: 2,
};

// Crownstone command types
export const CrownstoneCommandPacketType = {
  COMMAND_TYPE_SWITCH: 20,
};

// Crownstone result types
export const CrownstoneResultCodes = {
  SUCCESS: 0,
  WAIT_FOR_SUCCESS: 1,
  SUCCESS_NO_CHANGE: 2,
  BUFFER_UNASSIGNED: 16,
  BUFFER_LOCKED: 17,
  BUFFER_TOO_SMALL: 18,
  NOT_ALIGNED: 19,
  WRONG_PAYLOAD_LENGTH: 32,
  WRONG_PARAMETER: 33,
  INVALID_MESSAGE: 34,
  UNKNOWN_OP_CODE: 35,
  UNKNOWN_TYPE: 36,
  NOT_FOUND: 37,
  NO_SPACE: 38,
  BUSY: 39,
  WRONG_STATE: 40,
  ALREADY_EXISTS: 41,
  TIMEOUT: 42,
  CANCELED: 43,
  PROTOCOL_UNSUPPORTED: 44,
  MISMATCH: 45,
  WRONG_OPERATION: 46,
  NO_ACCESS: 48,
  UNSAFE: 49,
  NOT_AVAILABLE: 64,
  NOT_IMPLEMENTED: 65,
  NOT_INITIALIZED: 67,
  NOT_STARTED: 68,
  NOT_POWERED: 69,
  WRONG_MODE: 70,
  WRITE_DISABLED: 80,
  WRITE_NOT_ALLOWED: 81,
  READ_FAILED: 82,
  ADC_INVALID_CHANNEL: 96,
  EVENT_UNHANDLED: 112,
  GATT_ERROR: 128,
  UNSPECIFIED: 65535,
};
